### PR TITLE
Migrate user annotation state

### PR DESCRIPTION
**Pull request by ajyl**
Built DB model/table for user annotation state. 
Given the pretty big changes, this PR should only get merged once there's sufficient tests included...

### CODE REVIEW

**Comment by davidjurgens** [comment]
Wow! Looking forward to testing this one! I agree that we need to double check this pull request works before merging and breaking things. Perhaps we can label the version before/after too. Does this pull request depend on any of #18 #22 or #23 being merged first? (I'm not sure what their ready-to-merge status is right now)

**Comment by ajyl** [comment]
How about I just combined #18 and #22, where I'll use #18 to create some unittests for #22.
#23 should be ready to be merged, but needs to be rebased on #22.
This PR also needs to be rebased on #22, and I'll add some unittests for this PR as well.

**Comment by davidjurgens** [comment]
That sounds like a good plan to me. I'm also excited to have unit tests finally to make sure we're not breaking things when we make changes in the future. :)

**Comment by ajyl** [comment]
Also rebased on #23 , should be ready to be merged once all other PRs are merged!

**Pull request closed without merging**
