### PR TITLE
Refactoring user management

### PR DESCRIPTION
**Pull request by ajyl**
Got some major refactoring done.
A few new files:

- annotation_state_utils.py: Anything related to maintaining annotation state.
```
save_all_annotations()
update_annotation_state()
get_annotations_for_user_on()
get_span_annotations_for_user_on()
get_total_annotations()
```

- prestudy.py: Functions related to pre-study
- user_annotation_state.py: UserAnnotationState class.
- user_config.py: UserConfig class.
- user_state_utils.py: Anything related to maintaining user state.
```
lookup_user_state()
save_user_state()
load_user_state()
assign_instances_to_user()
move_to_prev_instance()
move_to_next_instance()
go_to_id()
```
- state.py: Global variables that are used across all these files (including flask_server.py)

Unfortunately, this PR is built on top of #20 ... Oops...

### CODE REVIEW

**Comment by ajyl** [comment]
Rebased on #20

**Comment by davidjurgens** [comment]
Overall this is looking good. For some context, we are (eventually) hoping to push all of this user-state-tracking stuff into something more persistent, like a SQL back-end, so it's easy to restart and handles any weird concurrency stuff that might come up when lots of folks are annotating. This latest change moves us in that direction since it _should_ be easier to start editing these classes/files to have the same contract but under the hood swap out what they do. That said, there's also issues of how easy it will be to easily and immediately run Potato locally (top priority) so maybe that's even something configurable in the long run?

**Comment by ajyl** [comment]
Ah -- I am glad to hear that there are plans to move to some sort of SQL back-end. I was looking at some easy options (cache, ["pysonDB lol"](https://github.com/pysonDB/pysonDB) etc.) but I was afraid there would be push-back given the additional complexity it introduces. I would love to be involved in any discussion around moving to persistent state tracking when the time comes (or if there are any already). Also happy to get a branch going if there hasn't been any efforts made yet.

**Comment by davidjurgens** [comment]
`pysondb` sounds like a great intermediate step to get us closer there. There's no current effort on this front, since we've been mostly hacking on the front-end features (there's a laundry list of stuff to do there too...) and haven't had a chance to really refactor the back-end.

In the long long term, we need to somehow retrofit the server to support 
* multiple tasks on the same server instance (currently one-task-per-instance)
* separate user/admin logins
* better user-facing stats/info, probably in overlays--stuff like their average time per instance and annotator aggreement
* an admin view that lets them change annotation setup, view annotator stats (e.g., spotting underperforming folks), and maybe do a bit more configuration.

All of those require more flexibility on the back-end and probably a longer-term overhaul. But for now, you can annotate easily with Potato for one-off tasks, which is 90% of our use-cases

**Review by davidjurgens — APPROVED** [review]

**Comment by davidjurgens** [comment]
Merged, which hopefully unblocks #22 and #23

**Pull request merged**
